### PR TITLE
add created meta files

### PR DESCRIPTION
**Pull request by corinnaj**
Add all missing .meta files created by unity

### CODE REVIEW

**Review by JotaroS — CHANGES_REQUESTED** [review]
Hey @corinnaj , there are a lot of meta files which are not even related to unity (e.g. `WindowsVoiceProject`, `NSSpeechForUnity`). `LICENSE.meta` should also not be related.

**Comment by corinnaj** [comment]
Good point, I guess those are only created when we add it as a submodule to our projects. I removed those files and added them to the gitignore instead.

**Comment by JotaroS** [comment]
@corinnaj hmmm I see `ProjectSettings/Physics2DSettings.asset.meta` file. Are all these related?

I would include all meta files that's __required__ to run for the new users: I don't think physics file matter?
Also, SpeechIOForUnity is completely script-based plugin. Scenes are optional and included in the `unitypackage` as https://github.com/HassoPlattnerInstituteHCI/SpeechIOForUnity/releases/tag/v1.0

Did you see something broken because the meta file is not included?

**Comment by corinnaj** [comment]
Since we are currently including this as a submodule in our PantoDoom Project, it creates all these files and then marks the submodule as dirty. I was somehow trying to prevent that (since it makes making commits more annoying in my opinion), but I see now that this might not be ideal I definitely didn't notice any problems due to the missing files.
I guess I can just track this branch with our project and keep it up to date. It  probably doesn't really make sense to merge it into master, since it's a very specific set of circumstances.

**Comment by JotaroS** [comment]
OK, i will close the issue for now ;)

**Pull request closed without merging**
