### PR TITLE
create speech out for linux, stub for speech in

### PR DESCRIPTION
**Pull request by corinnaj**
Create a basic speech out for linux using `espeak`, SpeechIn is stubbed for now, so the project does not error when included on linux

### CODE REVIEW

**Review by JotaroS — CHANGES_REQUESTED** [review]
Again, please keep the commit clean only for relevant changes.
Also, as this `master` branch is already public for outside (people are using this code), and things should be functionally released.
Let's mark the title as WIP, and try not to merge before it gets functional.

**Comment by corinnaj** [comment]
I removed the formatting changes. I added keytrigger to linux speech in. Even though it's not fully functional I'd like to merge it now, as currently I am getting error the PantoDoom project whenever I open it on Linux and it can't create the SpeechIn and SpeechOut.

**Review by JotaroS — APPROVED** [review]

**Comment by JotaroS** [comment]
OK merge it if that helps. Would you be responsible on implementing Linux support soon afterwards?

**Comment by corinnaj** [comment]
Feel free to tag me on issues that arise with the Linux implementation, however I think adding SpeechIn support is out of scope for me. I don't think an easily accessible API exists that supports this.

**Comment by JotaroS** [comment]
@corinnaj ah then should this be kept to another branch and your doom project use that branch: would that work?

**Comment by corinnaj** [comment]
My preferred solution would be to simply label linux as "partially support", merge this PR, and then see if the need for further work on Linux arises. As it stands right now, this will enable students that need or want to work on Linux have the baseline support of SpeechOut but no (proper) SpeechIn, which arguably will allow many projects, such as the Doom project, to be perfectly serviceable on Linux. As of right now, even if only SpeechOut is required or Speech support is optional, just including this as a dependency will lead to the project crashing.

Keeping it on separate branch will likely just mean that it won't be working with up-to-date versions of the other APIs soon enough, so that would make this PR obsolete.

I will include an update to the README as part of this PR in a commit in a moment.

**Pull request merged**
